### ISSUE TITLE
Packaged version on PyPi does not contain schema json files

### ISSUE THREAD

**Issue by stefanfoulis** [GordonSo/scimschema#2]
Using the library as installed from pypi currently does not work because the schema json files are not contained in the package:

```
In [6]: import scimschema
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-730f0f332a83> in <module>
----> 1 import scimschema

/virtualenv/lib/python3.6/site-packages/scimschema/__init__.py in <module>
----> 1 from .core_schemas import load_dict as _load_dict
      2 from . import core_schemas
      3 from ._model.schema_response import ScimResponse
      4 from ._model import scim_exceptions, model, attribute
      5

ModuleNotFoundError: No module named 'scimschema.core_schemas'
```

**Comment by amithorakeri** [comment]
@GordonSo I'm getting this error
ImportError: No module named scimschema
How to fix this? Any help would be very much appreciated

**Comment by GordonSo** [comment]
Hi @amithorakeri , sorry about this error. It appears the packaging fix hadn't worked as expected and it slipped through our ci coverage. Please upgrade to the latest version 0.1.45 for the newer package including the neccessary schemas and packages.

**Comment by amithorakeri** [comment]
Thanks for your quick response @GordonSo. The latest update, did fix the issue with scimshema module. But now, I'm getting below error

ImportError: cannot import name 'extension' from '__main__' (main.py)

**Comment by GordonSo** [comment]
Hi @amithorakeri I am guessing you have created a main.py file and try to run the code snippet copy and pasted from the readme? 

Since the extension package is different for each company, this should be defined/ created by you the engineer. However for the sake of demo, create a directory named extension at the root and copy and paste everything underneath https://github.com/GordonSo/scimschema/tree/master/tests/extension to see it working :) 

I have updated the steps: https://github.com/GordonSo/scimschema#example-use-case
But perhaps this could be still clearer in the readme, ideas to improve the understanding is welcome.

**Comment by amithorakeri** [comment]
@GordonSo Thanks a ton for responding to my queries. I will take a look at this and see if it's working.
