### ISSUE TITLE
Schema model returns Null for multi-valued attributes

### ISSUE THREAD

**Issue by mohankumaru** [GordonSo/scimschema#22]
please find the below code.

```
from scimschema import core_schemas

user_schema = core_schemas.schema['urn:ietf:params:scim:schemas:core:2.0:User']
for i in user_schema.attributes:
    print(i.name)
    print(i)
```
basically user_schema will be model object.

but it gives output like this,

```
userName
<scimschema._model.attribute.StringAttribute object at 0x03A386D0>
name
<scimschema._model.attribute.ComplexAttribute object at 0x03A38750>
displayName
<scimschema._model.attribute.StringAttribute object at 0x03A38790>
nickName
<scimschema._model.attribute.StringAttribute object at 0x03A38770>
profileUrl
<scimschema._model.attribute.ReferenceAttribute object at 0x03A387B0>
title
<scimschema._model.attribute.StringAttribute object at 0x03A388D0>
userType
<scimschema._model.attribute.StringAttribute object at 0x03A388F0>
preferredLanguage
<scimschema._model.attribute.StringAttribute object at 0x03A38910>
locale
<scimschema._model.attribute.StringAttribute object at 0x03A38930>
timezone
<scimschema._model.attribute.StringAttribute object at 0x03A388B0>
active
<scimschema._model.attribute.BooleanAttribute object at 0x03A38950>
password
<scimschema._model.attribute.StringAttribute object at 0x03A38970>
None
<scimschema._model.attribute.MultiValuedAttribute object at 0x03A38990>
None
<scimschema._model.attribute.MultiValuedAttribute object at 0x03A389F0>
None
<scimschema._model.attribute.MultiValuedAttribute object at 0x03A38AB0>
None
<scimschema._model.attribute.MultiValuedAttribute object at 0x03A38B70>
None
<scimschema._model.attribute.MultiValuedAttribute object at 0x03A38C30>
None
<scimschema._model.attribute.MultiValuedAttribute object at 0x03A38CF0>
None
<scimschema._model.attribute.MultiValuedAttribute object at 0x03A38E30>
None
<scimschema._model.attribute.MultiValuedAttribute object at 0x03A38EF0>
None
<scimschema._model.attribute.MultiValuedAttribute object at 0x03A38FB0>
```

**If you notice for multivalued objects i get NULL**,    there is something missing, could you please point out.

Regards,
Mohan

**Comment by GordonSo** [comment]
Hello, thanks for the interesting observation; the "missing" properties is due to the object structure of the schema model;
In the design, in order to comply to the specification's complex rules and properties definitions, there is a "MultiValued" attribute class which sits on top of other 'Data Type Attribute classes (e.g. string, complex etc). 

As such, the multiValuedAttribute merely represents a generic list (list<T>), and all its properties can be found in its 'element_attribute' property; so I think what you are looking for is in "element_attribute.name"

In your example, you can try: 
```user_schema.attributes[12].element_attribute.name```

Let me explain... the way the code evaluating the schema is from the top -> bottom, 

In the example, 
Lvl 1 - the schema is User, 
Lvl 2 - Attributes (let's examine the first MultiValuedAttribute (index 12), it is merely a representation for a generic list<T>
Lvl 3 - "element_attribute" property contains details about the list type, in this case it's a complex type with name: "email" <- I think this is what you are looking for.
Lvl 4 - The properties of such element is then defined as "subattributes", which is yet another list [for complex type]
Lvl 5 - There is a definitive set of datatype attributes, to represent "returns", "required" etc...

That said, I can see it can be confusing the multivalued level has different attribute to the child level; and we can "fix" that quite easily by reference its properties to its element_attribute's properties,

That way, the properties will be discoverable at both level 2 and 3.

See PR:
https://github.com/GordonSo/scimschema/pull/23/files#diff-761c77f14db7fd7b1534b8ab90c99b21R469-R478

Would this help you?

**Comment by mohankumaru** [comment]
Thank You  for your detailed explaination @GordonSo , that really helped.
