### ISSUE TITLE
API Framework Integration Examples and Custom Schema Configuration

### ISSUE THREAD

**Issue by shubhamyedage** [GordonSo/scimschema#6]
Hi,
I want to enable Python Flask APIs SCIM specific. Any documentation for usage of this lib  will be helpful.
Also if you can provide information about how to validate custom attribues in schema, that will be great.

**Comment by GordonSo** [comment]
Hey thanks for your comment. 

This library is pretty simple, you can create a python package containing your custom ("extension") schemas defined as per the rfc: https://tools.ietf.org/html/rfc7643#section-2. In the test module of this repo, we also provided some examples: https://github.com/GordonSo/scimschema/tree/master/tests/extension (note that the schema id must contain the word "extension" as per rfc example: "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User"

Then, you simply pass in the extension package into the 'validate' method and it will analyse the json data, by looping through the schemas id in the containing "schemas" attributes, and matching the corresponding json schema to validate the data accordingly.

There is an example outlined in the readme.md file for what's described above. 

But I would also suggest executing this test example if you are interested in running and debugging the working mechanism of the library: https://github.com/GordonSo/scimschema/blob/07bcd99934d70d2d8895e03dbafc59bdad081198/tests/test_scim_schema.py#L7

Hope this answers your question :)

ps: I think for the simplisty of this library, documentation is perhaps a little overkill at this stage; saying that we would welcome more test examples or readme descriptions to make the usage/ adoption smoother ;)

**Comment by GordonSo** [comment]
Upon a further read, I see there is a limitation in our library in only detecting extension schemas with name including 'extension'; it seems it should be acceptable for schema to be named otherwise - "urn:scim:my:custom:schema" as in the example provided in https://developers.onelogin.com/. 

One possible workaround would be to specify your custom schema with the extension convention for now, otherwise, it is actually very easy to extend that by modifying the way non-core schema is detected:
https://github.com/GordonSo/scimschema/blob/master/src/scimschema/_model/schema_response.py#L24-L30

I can find a look into that for you, but PR is also welcome if you beat me to it:

You can watch this ticket for progress:
https://github.com/GordonSo/scimschema/issues/7
